project:
  team: "hybrid"

deployment:
  enabled: true
  replicas: 1
  terminationGracePeriodSeconds: 60
  containerPort: 8000
  strategy:
    type: RollingUpdate
    maxUnavailable: 1
    maxSurge: 1
  autoscaling:
    enabled: false
  healthcheck:
    enabled: false
  ingress:
    enabled: true
    public: true
    hosts:
      - host: prebid-server.stg.connatix.com
        paths:
          - /
    tls: [ ]
    annotations: { }

containerSettings:
  resources:
    limits:
      cpu: "256m"
      memory: "256Mi"
    requests:
      cpu: "256m"
      memory: "256Mi"
  env:
    PBS_GDPR_ENABLED: true
    PBS_GDPR_DEFAULT_VALUE: true

    
    PBS_EXTERNAL_URL: https://prebid-server.stg.connatix.com
   
nodeSettings:
  useOnDemandInstances: false
  nodeRestrictions: "none"
  allowOtherAppsOnNode: true
  instanceTypes: []
  nodeGroups: [ "linux-multiaz-karpenter" ]
  arch: [ "amd64" ]
